# Add-on configuration for Home Assistant

name: "SL2HAr add-on"
version: "0.9"
slug: sl2har
description: SL2HAr add-on
url: "https://github.com/hwchaos/home-assistant_addons/sl2ha"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
# Add-on will start after Home Assistant.
startup: application

# Syslog port as UDP.
ports:
  514/udp: 514
ports_description:
  514/udp: "Port to listen logs"

# This add-on can access the Home Assistant REST API proxy
homeassistant_api: true

options:
  debug: false
  endpoint_1: "states/input_boolean.doorman"
  endpoint_2: "states/input_boolean.doorman"
  to_seek_1:
    pattern: "<\\d+:(\\w+)\\(\\d+\\)>"
    payload_template: '{"state": "{extracted}"}'
  to_seek_2:
    pattern: "Connection closed: (\\w+)"
    payload_template: '{"state": "{extracted}"}'

schema:
  debug: bool
  endpoint_1: str
  endpoint_2: str
  to_seek_1:
    type: dict
    keys:
      pattern: str
      payload_template: str
  to_seek_2:
    type: dict
    keys:
      pattern: str
      payload_template: str
